FROM node:22 AS node-build
WORKDIR /app

# Install packages first; need to install here to be cached in earlier layer
# and not trigger re-compiles if only source code changes
COPY package.json package-lock.json /app/
RUN npm ci

# Copy the source code into the container
COPY \
  .browserslistrc \
  .nvmrc \
  .editorconfig \
  jsconfig.json \
  vite.config.mjs \
  index.html \
  /app/

COPY public /app/public
COPY src /app/src

LABEL org.label-schema.name="colocus-ui"
LABEL org.label-schema.description="Development image for Colocus UI"
LABEL org.label-schema.vendor="University of Michigan, Center for Statistical Genetics"
LABEL org.label-schema.url="https://github.com/statgen/colocus-ui-vue3"
LABEL org.label-schema.usage="https://github.com/statgen/colocus-ui-vue3#docker"
LABEL org.label-schema.vcs-url="https://github.com/statgen/colocus-ui-vue3"
LABEL org.label-schema.schema-version="1.0"

ARG BUILD_DATE
ARG GIT_SHA
ARG COLOCUS_UI_VERSION

LABEL org.label-schema.version=$COLOCUS_UI_VERSION \
      org.label-schema.vcs-ref=$GIT_SHA \
      org.label-schema.build-date=$BUILD_DATE

CMD ["sh", "-c", "node --no-warnings ./node_modules/.bin/vite --host 0.0.0.0 --port ${VITE_PORT:-5173} --strictPort"]
